set number
set mouse=a
set smarttab
set cindent
set tabstop=2
set shiftwidth=2
set expandtab

set background=dark
set termguicolors
syntax on
colorscheme oceanicnext

filetype plugin indent on

inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

map <C-n> :NERDTreeToggle<CR>
map <C-l> :Limelight!!0.8<CR>

set laststatus=2
set noshowmode
let g:lightline = { 'colorscheme': 'oceanicnext' }
